#!/usr/bin/env node
// Render a component guide (Markdown + front matter) to a standalone web page, and optionally PDF.
//
//   node tools/render-doc.mjs <doc.md> <out.html> [--pdf out.pdf] [--draft]
//
// Images are referenced relative to the Markdown file, so keep out.html next to its img/ folder.
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { parseDoc, sections, renderMarkdown, page, escapeHtml } from './lib/doc-render.mjs';

const args = process.argv.slice(2);
const [src, out] = args.filter((a, i) => !a.startsWith('--') && args[i - 1] !== '--pdf');
const pdfOut = args.includes('--pdf') ? args[args.indexOf('--pdf') + 1] : null;
const isDraft = args.includes('--draft');
const fragment = args.includes('--fragment');
if (!src || !out) {
  console.error('usage: render-doc.mjs <doc.md> <out.html> [--pdf out.pdf] [--draft] [--fragment]');
  process.exit(2);
}

const { meta, body } = parseDoc(fs.readFileSync(src, 'utf8'));
const html = renderMarkdown(body);
const toc = sections(body).filter((s) => s.title !== '_intro')
  .map((s) => `<li><a href="#${s.id}">${renderMarkdown(s.title).replace(/<\/?p>/g, '').trim()}</a></li>`).join('');

const ticket = meta.ticket ? `<span>Ticket: ${meta.ticket.url ? `<a href="${meta.ticket.url}">${escapeHtml(meta.ticket.id)}</a>` : escapeHtml(meta.ticket.id)}</span>` : '';
const header = `
<header class="doc-header"><div class="inner">
  <div class="crumbs"><a href="#">Component guides</a> / ${escapeHtml(meta.group || 'Components')}</div>
  <h1>${escapeHtml(meta.title || 'Component guide')}</h1>
  <div class="meta">
    <span class="pill${isDraft ? ' draft' : ''}">${isDraft ? 'Draft ' : ''}${escapeHtml(meta.version || 'v1')}</span>
    <span>Updated ${escapeHtml(meta.date || '')}</span>
    ${meta.templateId ? `<span><code>${escapeHtml(meta.templateId)}</code></span>` : ''}
    ${ticket}
  </div>
</div></header>`;

const doc = page({
  fragment,
  title: meta.title || 'Component guide',
  body: `${header}
<div class="layout">
  <nav class="toc" aria-label="On this page"><h4>On this page</h4><ol>${toc}</ol></nav>
  <main class="doc">
    ${html}
    <div class="doc-footer">Generated by On-Demand Documentation from a live Magnolia session${meta.magnolia ? ` (${escapeHtml(meta.magnolia)})` : ''}. Screenshots captured ${escapeHtml(meta.date || '')}.</div>
  </main>
</div>`,
});

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, doc);
console.log(`HTML: ${out}`);

if (pdfOut) {
  const browser = await chromium.launch();
  const p = await browser.newPage();
  await p.goto('file://' + path.resolve(out), { waitUntil: 'networkidle' });
  await p.emulateMedia({ media: 'print', colorScheme: 'light' });
  await p.pdf({ path: pdfOut, format: 'A4', printBackground: true, margin: { top: '16mm', bottom: '16mm', left: '14mm', right: '14mm' },
    displayHeaderFooter: true, headerTemplate: '<span></span>',
    footerTemplate: `<div style="font:9px Inter,sans-serif;color:#888;width:100%;padding:0 14mm;display:flex;justify-content:space-between"><span>${escapeHtml(meta.title || '')} · ${escapeHtml(meta.version || '')}</span><span class="pageNumber"></span></div>` });
  await browser.close();
  console.log(`PDF: ${pdfOut}`);
}
